from circularlist import CircularLists

dl= CircularLists()
print(f"dl Esta vacia? {dl.is_empty()}")
dl.get_size()
dl.insert(10)
dl.insert(15)
dl.insert(8)
dl.insert(9)
dl.insert(20)
dl.insert(11)
dl.transversal()
print(f"Elemento {dl.search()}")
print(f"Elemento {dl.search(8)}")
print(f"Elemento {dl.search(20)}")
# valor=int(input("Ingresa el elemento a buscar: "))
# print(f"Elemento {valor} {dl.search(valor)}")
dl.insert(20)
dl.insert(15)
dl.insert(38)
dl.insert()
dl.get_size()
print(f"dl Esta vacia? {dl.is_empty()}")
dl.remove(8)
dl.remove(11)
dl.remove(10)
dl.transversal()
dl.get_size()
dl.get_ref()
