from CircularList2 import CircularListsDouble

ld= CircularListsDouble()
ld.insert(10)
ld.insert(8)
ld.insert(15)
ld.insert(4)
ld.insert(12)
ld.transversal()
print(f"Lista vacias? ==> {ld.is_empty()}")
ld.get_size()
ld.remove(15)
ld.insert(10)
ld.insert(30)
# ld.remove(8)
# ld.remove(12)
# ld.remove(15)
#ld.remove(10)
print(ld.search(15))
ld.get_ref()
print(f"Elemento 15 {ld.search(15)}")
print(f"Elemento 8 {ld.search(8)}")
ld.remove(4)
ld.transversal()
ld.get_size()
